"use client";
import {useEffect,useMemo,useState} from "react";
import {campaign} from "../data/campaign";
const cash=(n:number,decimals=0)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",minimumFractionDigits:decimals,maximumFractionDigits:decimals}).format(n);
const Arrow=()=> <span aria-hidden>↗</span>;
const Label=({n,label}:{n:string,label:string})=><div className="section-label">{n} / {label}</div>;

export default function Home(){
 const [menu,setMenu]=useState(false),[records,setRecords]=useState(false);
 const progress=useMemo(()=>campaign.raisedAmount/campaign.targetAmount*100,[]);
 const remaining=campaign.targetAmount-campaign.raisedAmount;
 const perCharity=campaign.raisedAmount/campaign.charities.length;
 const charityProgress=perCharity/campaign.charityTarget*100;
 useEffect(()=>{const els=document.querySelectorAll("[data-reveal]");const ob=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("visible")),{threshold:.08});els.forEach(e=>ob.observe(e));return()=>ob.disconnect()},[]);
 useEffect(()=>{document.body.style.overflow=menu||records?"hidden":"";return()=>{document.body.style.overflow=""}},[menu,records]);
 const nav=[["Progress","#progress"],["How it works","#how-it-works"],["Charities","#charities"],["Records","#records"],["Past events","#events"]];
 return <>
 <header><a className="brand" href="#top"><span className="mark"><i/><i/><i/></span>THE SLICE CHALLENGE</a><nav className={menu?"open":""}>{nav.map(x=><a key={x[1]} href={x[1]} onClick={()=>setMenu(false)}>{x[0]}</a>)}<a className="btn small" href="#charities">Donate <Arrow/></a></nav><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Toggle menu" aria-expanded={menu}><i/><i/></button></header>
 <main id="top">
  <section className="hero"><div className="hero-copy" data-reveal><p className="eyebrow"><i/>Pizza with a purpose</p><h1>EVERY SLICE<br/>COUNTS TOWARDS<br/><em>£100,000.</em></h1><p className="intro">Every pizza costs £12. £7 goes to charity and £5 covers the cost of making it. We have sold {campaign.pizzasSold} pizzas and raised {cash(campaign.raisedAmount)} for charity so far.</p><div className="actions"><a className="btn" href="#charities">Donate directly <Arrow/></a><a className="btn outline" href="#how-it-works">See the breakdown ↓</a></div><ul className="trust"><li>£12 per pizza</li><li>£7 to charity</li><li>£5 covers costs</li></ul></div>
  <aside className="target-card" data-reveal><div className="cardline"><span>Current total</span><span className="live">Updated</span></div><div className="target"><small>Raised for charity</small><strong>{cash(campaign.raisedAmount)}</strong></div><div className="card-stats"><div><small>Pizzas sold</small><b>{campaign.pizzasSold}</b></div><div><small>Overall target</small><b>£100K</b></div></div><div className="mini-track"><i style={{width:`${progress}%`}}/></div><p className="no-limit"><b>£7</b> from every pizza is added to the charity total.</p></aside></section>

  <section className="progress dark" id="progress"><Label n="01" label="Campaign progress"/><div className="heading" data-reveal><div><p className="eyebrow"><i/>Current total</p><h2>£182 RAISED.<br/>26 PIZZAS.</h2></div><p>{campaign.pizzasSold} pizzas × {cash(campaign.charityPerPizza)} for charity = {cash(campaign.raisedAmount)}.</p></div><div className="counter" data-reveal><strong>{cash(campaign.raisedAmount)}</strong><span>/ {cash(campaign.targetAmount)}</span></div><div className="progressbar" role="progressbar" aria-valuenow={progress} aria-valuemax={100}><i style={{width:`${progress}%`}}/></div><div className="metrics"><div><small>Raised for charity</small><b>{cash(campaign.raisedAmount)}</b></div><div><small>Completed</small><b>{progress.toFixed(3)}%</b></div><div><small>Still to raise</small><b>{cash(remaining)}</b></div><div><small>Pizzas sold</small><b>{campaign.pizzasSold}</b></div></div></section>

  <section className="how cream" id="how-it-works"><Label n="02" label="How it works"/><div className="split" data-reveal><h2>ONE PIZZA.<br/><em>£7 DONATED.</em></h2><p>The price and split are fixed, so it is clear what happens to the money from each sale.</p></div><div className="steps price-steps"><article data-reveal><span>01</span><i/><h3>£12 Sale</h3><p>The customer pays £12 for one pizza.</p></article><article data-reveal><span>02</span><i/><h3>£5 Costs</h3><p>£5 covers ingredients, packaging and the cost of making the pizza.</p></article><article data-reveal><span>03</span><i/><h3>£7 Charity</h3><p>£7 is added to the campaign’s charity total.</p></article></div></section>

  <section className="charities dark" id="charities"><Label n="03" label="10 charity targets"/><div className="split" data-reveal><h2>£10,000<br/><em>FOR EACH.</em></h2><p>The £100,000 target is split equally across ten charities. Each charity has a £10,000 target and currently has {cash(perCharity,2)} recorded.</p></div><div className="charity-grid ten">{campaign.charities.map((c,i)=><article key={c.name} data-reveal><div className="logo-ph">{String(i+1).padStart(2,"0")}</div><small>CHARITY {String(i+1).padStart(2,"0")}</small><h3>{c.name}</h3><p>{c.description}</p><div className="charity-money"><span>Donated so far</span><b>{cash(perCharity,2)}</b><small>of {cash(campaign.charityTarget)}</small><i><u style={{width:`${charityProgress}%`}}/></i></div><a href={c.url} target="_blank" rel="noreferrer">Donate on official site <Arrow/></a></article>)}</div><div className="charity-total"><span>Total across all 10 charities</span><b>{cash(campaign.raisedAmount)}</b><small>{cash(perCharity,2)} each</small></div><p className="note">Direct donation buttons open each charity’s official website. Direct donations made there are handled by that charity and are not automatically included in The Slice Challenge total.</p></section>

  <section className="transparency red" id="records"><Label n="04" label="Charity records"/><div className="ledger-grid"><div data-reveal><p className="eyebrow"><i/>The split</p><h2>EVERY<br/><em>£182.</em></h2><p>The current charity total is divided equally between the ten charities: {cash(campaign.raisedAmount)} ÷ 10 = {cash(perCharity,2)} per charity.</p><button className="btn cream-btn" onClick={()=>setRecords(true)}>View full records <Arrow/></button></div><div className="ledger charity-ledger" data-reveal><div className="ledger-head"><span>Ref</span><span>Charity</span><span>Donated</span><span>Target</span></div>{campaign.charities.map((c,i)=><div className="ledger-row" key={c.name}><span>CH-{String(i+1).padStart(2,"0")}</span><span>{c.name}</span><span>{cash(perCharity,2)}</span><span>{cash(campaign.charityTarget)}</span></div>)}<div className="ledger-total"><span>Total donated</span><b>{cash(campaign.raisedAmount)}</b></div></div></div></section>

  <section className="events cream" id="events"><Label n="05" label="Past events"/><div className="split" data-reveal><h2>PAST<br/><em>EVENTS.</em></h2><p>Pizza sales and the charity amount raised at each event.</p></div><div className="event-list">{campaign.events.map((e,i)=><article key={e.name} data-reveal><span>0{i+1}</span><div><small>EVENT</small><h3>{e.name}</h3><p>{e.note}</p></div><div><small>PIZZAS SOLD</small><b>{e.pizzas}</b></div><div><small>RAISED FOR CHARITY</small><b>{cash(e.raised)}</b></div></article>)}</div></section>

  <section className="connect"><Label n="06" label="Contact"/><div className="connect-grid"><div data-reveal><p className="eyebrow"><i/>Follow</p><h2>KEEP UP<br/><em>WITH IT.</em></h2></div><div className="simple-links" data-reveal><a href={campaign.instagramUrl} aria-label="The Slice Challenge on Instagram"><small>Social</small><b>Instagram</b><Arrow/></a><a href={`mailto:${campaign.email}`}><small>Contact</small><b>Email us</b><Arrow/></a><div><small>Sponsors</small><b>No sponsors yet</b><span>—</span></div></div></div></section>
 </main>
 <footer><div className="footer-top"><div><a className="brand" href="#top"><span className="mark"><i/><i/><i/></span>THE SLICE CHALLENGE</a><h2>Pizza with<br/>a purpose.</h2></div><div className="footer-links"><div><p>Navigate</p>{nav.map(x=><a key={x[1]} href={x[1]}>{x[0]}</a>)}</div><div><p>Connect</p><a href={campaign.instagramUrl}>Instagram</a><a href={`mailto:${campaign.email}`}>{campaign.email}</a></div><div><p>Site</p><a href="https://theslicechallenge.com">theslicechallenge.com</a></div></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} The Slice Challenge</span><p>Campaign totals are updated when pizza sales and charity allocations are recorded. Direct donations made on charity websites are not included automatically.</p><a href="#top">Back to top ↑</a></div></footer>
 {records&&<div className="modal-bg" onMouseDown={()=>setRecords(false)}><div className="modal records-detail" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setRecords(false)} aria-label="Close">×</button><p className="eyebrow"><i/>Campaign records</p><h2>£182<br/>RECORDED.</h2><p><b>Helen & John’s Wedding</b><br/>26 pizzas sold at £12 each. £7 per pizza went to the charity total and £5 per pizza covered costs.</p><div><span>Pizza sales</span><b>26 × £12 = £312</b></div><div><span>Costs covered</span><b>26 × £5 = £130</b></div><div><span>Raised for charity</span><b>26 × £7 = £182</b></div><button className="btn" onClick={()=>setRecords(false)}>Close records</button></div></div>}
 </>
}
